# Generated by Django 5.0.14 on 2026-08-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos_alter_comentario_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
    ]
